# Generated by Django 4.0.3 on 2022-05-02 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ip_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('ip', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'IP address',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Link_only_ip_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=50)),
                ('device', models.CharField(default='None', max_length=100)),
                ('country', models.CharField(default='None', max_length=50)),
                ('click', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.links')),
            ],
            options={
                'verbose_name_plural': 'Link',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('click', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.links')),
            ],
            options={
                'verbose_name': 'Analytics',
                'verbose_name_plural': 'Analytics',
                'ordering': ['-date'],
            },
        ),
    ]
