# Generated by Django 4.0.3 on 2022-11-14 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_analytics_country_analytics_device_analytics_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='country',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='device',
        ),
    ]
