# Generated by Django 4.0.3 on 2022-11-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_remove_analytics_country_remove_analytics_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='user',
        ),
    ]
